baseURL = "https://prakash2403.github.io/"
languageCode = "en-us"
title = "Information Theory | Statistical Mechanics | Machine Learning"
theme="hugo-theme-dream"

[params]
    author= "Prakash"
    avatar= "/me/profile.jpg"
    motto= "Lazy | Math Nerd | Potterhead | Data Scientist"
    github= "Prakash2403"

